### ISSUE TITLE
NotoSansMongolian Unfamiliar glyph U+1837 RA 

### ISSUE THREAD

**Issue by KazunariTsuboi** [notofonts/mongolian#2]
### Font
NotoSansMongolian-Regular.ttf
https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSansMongolian

### Font Version
Version 2.000

### Character data
ᠷ  　　U+1837 MONGOLIAN LETTER RA

### Issue
The letter RA needs to have the shape adjusted the lower, inner, downwards bent stroke needs to be a shorter straight stroke on the lefts side instead of the right side.
The glyph of Unicode chart or, such as the glyph of "Mongolian Baiti" used in Windows, are desirable design.

**NotoSans Mongolian**
![image](https://user-images.githubusercontent.com/21096794/61025394-8bd2c980-a3eb-11e9-9394-9a9909aa057f.png)

**Mongolian Baiti**
![image](https://user-images.githubusercontent.com/21096794/61025413-9c833f80-a3eb-11e9-953e-0b96d1254358.png)

**Unicode.org chart**
![image](https://user-images.githubusercontent.com/21096794/61025438-b755b400-a3eb-11e9-8e65-9d9d9c7a92b4.png)

**Comment by simoncozens** [comment]
Thank you, that makes sense! It looks like if anything it would be an issue for a stylistic set but for now I'm happy for the "Mongolian" form to have preference.

**Comment by Tosche** [comment]
I think 'more popular in Mongolia' might have been misleading; even in Mongolia, the current form is probably in the minority if I take statistics (it's just found more in Mongolia and historically justifiable than it is in China)

**Comment by KazunariTsuboi** [comment]
I have experience in distributing Noto fonts with custom RA shapes to an unspecified number of Mongolian-speaking people (regions are not specific locations). As far as I know, there have been no complaints about RA's custom shape, which has been used for several years. Of course, I want a better design by the designer (natives must want it too).
 I hope this information will be of some help.
![image](https://user-images.githubusercontent.com/21096794/176220689-d6cf5419-9a7e-4396-bc06-f93e661204a3.png)

**Comment by simoncozens** [comment]
Fixed in #33. Will be released this quarter.
