### ISSUE TITLE
Maybe some errors in your test case.

### ISSUE THREAD

**Issue by jsj05514** [notofonts/mongolian#24]
My computer environment and Screenshots
<img width="270" alt="微信截图_20221021214524" src="https://user-images.githubusercontent.com/49635733/197213281-30498f41-b57b-4b5f-a088-fc49a7852e48.png">
<img width="645" alt="微信截图_20221021214211" src="https://user-images.githubusercontent.com/49635733/197213298-69589432-662c-447e-95ec-67f1a7d68aaf.png">
<img width="636" alt="微信截图_20221021213601" src="https://user-images.githubusercontent.com/49635733/197213302-31c39575-8bd6-4780-aef5-5a8c742c318a.png">

**Comment by simoncozens** [comment]
Fixed in #33. Will be released this quarter.
