### ISSUE TITLE
Shaping errors in Todo writing system

### ISSUE THREAD

**Issue by Kushim-Jiang** [notofonts/mongolian#25]
1. The medial ___u___ after ___u___ is fine (ᡇᡇᠷ), but the final ___u___ after ___u___ has not be implemented.

![image](https://user-images.githubusercontent.com/26769129/198291007-8ccf9735-80d4-4384-bcfa-aabb5f693273.png)
![image](https://user-images.githubusercontent.com/26769129/198291065-9f047204-a721-4d35-94ef-7da73d632c97.png)
![image](https://user-images.githubusercontent.com/26769129/198291119-8988f60d-597a-4346-b8e2-b78095baa7e0.png)

2. The long vowels ___aa___ (ᠠᡃ), ___ee___ (ᡄᡃ) and ___oo___ (ᡆᡃ) are shaped wrongly.

![image](https://user-images.githubusercontent.com/26769129/198291517-dc6c36fa-c855-489e-ad93-22b32732b4b0.png)
![image](https://user-images.githubusercontent.com/26769129/198291618-77fad57a-947a-437d-b9d3-dd3af5b7b114.png)
![image](https://user-images.githubusercontent.com/26769129/198291715-a7dcb525-499f-4616-b44b-444eac83f365.png)
![image](https://user-images.githubusercontent.com/26769129/198291832-dcd911dc-e49e-453e-8097-9395d6fd20aa.png)

**Comment by simoncozens** [comment]
Fixed in #33. Will be released this quarter.
