### ISSUE TITLE
Contextual Form Error for Manchu Final -ko/ho

### ISSUE THREAD

**Issue by tyotakuki** [notofonts/mongolian#26]
### Contextual Form Error for Manchu Final -ko/ho
The final _waw_ (U+1823 Mongolian Letter O) of Manchu endings -ko and -ho should expect to have a tail, as in the following two correct examples "coko" and "oho":
<img width="326" alt="image" src="https://user-images.githubusercontent.com/20675056/202837979-dff648e0-62e4-477e-92df-22a46273e9cf.png">
However, the incorrect contextual form given by Noto Sans Mongolian produces:
<img width="317" alt="image" src="https://user-images.githubusercontent.com/20675056/202838048-aa64cc9b-74fc-4d77-bcc7-4c237ef60be4.png">

### How to fix:
In Manchu, the final _waw_ (U+1823 Mongolian Letter O) without tail only appears in monosyllabic words without diphthongs. For example:
<img width="490" alt="image" src="https://user-images.githubusercontent.com/20675056/202838364-d0d06e0b-7ac0-4a56-b4d1-e769212f28aa.png">
In Unicode, the final _waw_ without tail should be produced by U+1823 U+180B (Mongolian Letter O + FVS1). In multisyllabic words and monosyllabic words with diphthongs like -eo, -io, -oo, the final _waw_ should always have a tail.
<img width="751" alt="image" src="https://user-images.githubusercontent.com/20675056/202838585-d112eb7f-5bda-402d-9144-675c152645ef.png">

**Comment by simoncozens** [comment]
Fixed in #33. Will be released this quarter.
