### ISSUE TITLE
Wrong shape for Manchu "ku"

### ISSUE THREAD

**Issue by nikkiwd** [notofonts/mongolian#28]
### Font 

NotoSansMongolian-Regular.ttf

### Where the font came from, and when

https://github.com/notofonts/mongolian/releases/tag/NotoSansMongolian-v2.003

### Font Version

2.003

### OS name and version

Observed in both Ubuntu and Windows 10

### Issue

Manchu "ku" in the word "ᠪᡠᠯᡝᡴᡠ" (buleku) has the wrong shape.

It renders as:

![buleku](https://github.com/notofonts/mongolian/assets/18699222/ba38b347-d4f0-4652-b4c4-a28c4dfce573)

instead of like this (using Mongolian Baiti):

![buleku](https://github.com/notofonts/mongolian/assets/18699222/bd555586-720e-4e0f-8fff-e473131ac39e)

### Character data

U+‎182A BA
U+‎1860 SIBE UE
U+182F LA
U+185D SIBE E
U+1874 MANCHU KA
U+1860 SIBE UE

**Comment by simoncozens** [comment]
We are in the process of having a completely new shaping approach for the Mongolian font, so I hope this (and similar) issues will be resolved soon. More information as I get it!

**Comment by simoncozens** [comment]
Fixed in #33. Will be released this quarter.
