### ISSUE TITLE
Manchu "de" and "du" have two dots instead of only one

### ISSUE THREAD

**Issue by nikkiwd** [notofonts/mongolian#29]
### Font

NotoSansMongolian-Regular.ttf

### Where the font came from, and when

https://github.com/notofonts/mongolian/releases/tag/NotoSansMongolian-v2.003

### Font Version

2.003

### OS name and version

Observed in both Ubuntu and Windows 10

### Issue

Manchu "de" has two dots instead of only one.

The word "ᡩᡝ" (de) renders as:

![de](https://github.com/notofonts/mongolian/assets/18699222/8ce95f1d-77f1-4428-9d40-8c39223ecab3)

and the word "ᡩᡝᠮᠪᡝᡳ" (dembei) renders as:

![dembei](https://github.com/notofonts/mongolian/assets/18699222/3bb8171a-facf-4bf4-8361-e3d76b441957)

How they're rendered in Mongolian Baiti:

![de](https://github.com/notofonts/mongolian/assets/18699222/9ab86582-9d97-4f90-a7b1-37e44fdfd46e)

![dembei](https://github.com/notofonts/mongolian/assets/18699222/fb4aee2d-7e71-4028-9e86-f07f75a7cd78)

### Character data

U+‎1869 MONGOLIAN LETTER SIBE DA
U+185D MONGOLIAN LETTER SIBE E

and

U+‎1869 MONGOLIAN LETTER SIBE DA
U+185D MONGOLIAN LETTER SIBE E
U+182E MONGOLIAN LETTER MA
U+182A MONGOLIAN LETTER BA
U+185D MONGOLIAN LETTER SIBE E
U+1873 MONGOLIAN LETTER MANCHU I

**Comment by nikkiwd** [comment]
"du" has the same problem:

"ᡨᡠ" (du):

![du](https://github.com/notofonts/mongolian/assets/18699222/e6edc715-d8c9-4f1e-94c1-cfd2dbcbbba9)

"ᡩᡠᠨᡝᠨ" (dunen):

![dunen](https://github.com/notofonts/mongolian/assets/18699222/141729fe-2ec0-42b0-a9f3-064e3351a308)

Both words in Mongolian Baiti:

![du](https://github.com/notofonts/mongolian/assets/18699222/adfa49f6-3e1d-4476-b453-ec042301e193)

![dunen](https://github.com/notofonts/mongolian/assets/18699222/917a6980-df5f-43ed-a5e2-edda8e85eb6f)

Characters:
U+1869 MONGOLIAN LETTER SIBE DA
U+1860 MONGOLIAN LETTER SIBE UE
U+1828 MONGOLIAN LETTER NA
U+185D MONGOLIAN LETTER SIBE E
U+1828 MONGOLIAN LETTER NA

**Comment by gwjjanggu** [comment]
There are also issues displaying ku/gu/hu after e, and k after ku/gu/hu.
![屏幕截图 2023-10-03 232218](https://github.com/notofonts/mongolian/assets/72967140/a594fc8f-f812-466e-a4b4-c63dcedde8ea)

**Comment by simoncozens** [comment]
Fixed in #33. Will be released this quarter.
