### ISSUE TITLE
Medial "gl" does not render clearly

### ISSUE THREAD

**Issue by nikkiwd** [notofonts/mongolian#30]
### Font

NotoSansMongolian-Regular.ttf

### Where the font came from, and when

https://github.com/notofonts/mongolian/releases/tag/NotoSansMongolian-v2.003

### Font Version

2.003

### OS name and version

Observed in both Ubuntu and Windows 10

### Issue

-gl- in a word such as "ᠠᠩᠭᠯᠢ" (anggli) does not render clearly. Instead of only the base of the l being attached to the g, the entire letter overlaps the g, leaving only a small gap in the corner.

The word renders as:

![anggli](https://github.com/notofonts/mongolian/assets/18699222/cb37a8d7-c761-42de-86e7-ce1fb1776877)

How it's rendered in Menk Qagan Tig:

![anggli](https://github.com/notofonts/mongolian/assets/18699222/fc9bd475-1e69-4931-9ad4-fb6844e61dd4)

and in Oyun Qagan Tig:

![anggli](https://github.com/notofonts/mongolian/assets/18699222/aa88d1e9-b53a-40c9-b0a1-f8fc48ec7b81)

### Character data

U+1820 MONGOLIAN LETTER A
U+1829 MONGOLIAN LETTER ANG
U+182D MONGOLIAN LETTER GA
U+182F MONGOLIAN LETTER LA
U+1822 MONGOLIAN LETTER I

**Comment by simoncozens** [comment]
Fixed in #33. Will be released this quarter.
