### ISSUE TITLE
Wrong shape for Manchu "f" before i/o/u

### ISSUE THREAD

**Issue by nikkiwd** [notofonts/mongolian#31]
### Font 

NotoSansMongolian-Regular.ttf

### Where the font came from, and when

https://github.com/notofonts/mongolian/releases/tag/NotoSansMongolian-v2.003

### Font Version

2.003

### OS name and version

Observed in both Ubuntu and Windows 10

### Issue

Manchu "f" should have the same shape as "w" before "i", "o" and "u", but in some words it doesn't.

Examples (Noto Sans Mongolian and Mongolian Baiti):

"ᠨᠣᡶᡳ" (nofi)

![nofi](https://github.com/notofonts/mongolian/assets/18699222/08d8396e-4c06-4712-af3b-00133eb66401)

"ᡝᡶᡠ" (efu)

![efu](https://github.com/notofonts/mongolian/assets/18699222/d31fb812-5347-48fe-bc90-f6fe5f0f7702)

"ᠵᠠᡶᡠ" (jafu)

![jafu](https://github.com/notofonts/mongolian/assets/18699222/1f1f2799-b79a-463c-a14e-ce715e218df3)

### Character data

U+1828 MONGOLIAN LETTER NA
U+1823 MONGOLIAN LETTER O
U+1876 MONGOLIAN LETTER MANCHU FA
U+1873 MONGOLIAN LETTER MANCHU I

and

U+185D MONGOLIAN LETTER SIBE E
U+1876 MONGOLIAN LETTER MANCHU FA
U+1860 MONGOLIAN LETTER SIBE UE

and

U+1835 MONGOLIAN LETTER JA
U+1820 MONGOLIAN LETTER A
U+1876 MONGOLIAN LETTER MANCHU FA
U+1860 MONGOLIAN LETTER SIBE UE

**Comment by simoncozens** [comment]
Fixed in #33. Will be released this quarter.
